Login_App/urls.py
from django.urls import path
from Login_App import views

app_name = "Login_App"

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('edit/', views.editprofile_view, name='edit'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('user/<username>/', views.user_view, name='user'),
    path('follow/<username>/', views.follow_view,name='follow'),
    path('unfollow/<username>/', views.unfollow_view, name='unfollow'),
]

Socl_Mdia_Proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from Posts_App import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('Login_App.urls')),
    path('posts/', include('Posts_App.urls')),
    path('', views.home, name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Login_App/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserprofileModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    description = models.TextField(blank=True)
    full_name = models.CharField(max_length=264, blank=True)
    date_of_birth = models.DateField(blank=True, null=True)
    website = models.URLField(blank=True)
    facebook = models.URLField(blank=True)

    def __str__(self) -> str:
        return self.user 
    

class FollowerModel(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower') # Who is following me
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following') # wWhom I'm following
    created_date = models.DateTimeField(auto_now_add=True)

Login_App/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from Login_App.models import UserprofileModel

class CreateUserForm(UserCreationForm):
    email = forms.EmailField(required=True, label="", widget=forms.TextInput(attrs={'placeholder':'Email'}))
    username = forms.CharField(required=True, label="", widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password1 = forms.CharField(required=True, label="", widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
    password2 = forms.CharField(required=True, label="", widget=forms.PasswordInput(attrs={'placeholder':'Password Confirmation'}))

    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2')


class EditProfile(forms.ModelForm):
    date_of_birth = forms.DateField(widget=forms.TextInput(attrs={'type':'date',}))

    class Meta:
        model = UserprofileModel
        exclude = ('user',)

Login_App/views.py
from django.shortcuts import render, HttpResponseRedirect
from Login_App.models import UserprofileModel, FollowerModel
from Login_App.forms import CreateUserForm, EditProfile
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from Posts_App.forms import PostForm

# Create your views here.

def signup_view(request):
    form = CreateUserForm()
    registered = False

    if request.method == 'POST':
        form = CreateUserForm(data=request.POST)

        if form.is_valid():
            user = form.save()
            registered = True
            user_profile = UserprofileModel(user=user)
            user_profile.save()
            
            return HttpResponseRedirect(reverse('Login_App:login'))

    return render(request, 'Login_App/signup.html', context={'title':'SignUp', 'form':form, 'registered':registered})


def login_view(request):
    form = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            
            user = authenticate(username=username, password=password)
            
            if user is  not None:
                login(request, user)
                return HttpResponseRedirect(reverse('Posts_App:home'))

    return render(request, 'Login_App/login.html', context={'title':'Login', 'form':form})


@login_required
def editprofile_view(request):
    current_user = UserprofileModel.objects.get(user=request.user)
    form = EditProfile(instance=current_user)

    if request.method == 'POST':
        form = EditProfile(request.POST, request.FILES, instance=current_user)
        
        if form.is_valid():
            form.save(commit=True)
            form = EditProfile(instance=current_user)
            return HttpResponseRedirect(reverse('Login_App:profile'))

    return render(request, 'Login_App/profile.html', context={'title':'Profile', 'form':form})


@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('Login_App:login'))


@login_required
def profile_view(request):
    form = PostForm
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid:
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('Posts_App:home')) 
    return render(request, 'Login_App/user.html', context={'title':'Profile', 'form': form})

@login_required
def user_view(request, username):
    user_other = User.objects.get(username=username)
    already_followed = FollowerModel.objects.filter(follower=request.user, following=user_other)
    if user_other == request.user:
        return HttpResponseRedirect(reverse('Login_App:profile'))
    return render(request, 'Login_App/user_other.html', context={'user_other':user_other, 'title': username, 'already_followed':already_followed})

@login_required
def follow_view(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = FollowerModel.objects.filter(follower=follower_user, following=following_user)

    if not already_followed:
        followed_user = FollowerModel(follower=follower_user, following=following_user)
        followed_user.save()
    return HttpResponseRedirect(reverse('Login_App:user', kwargs={'username':username}))

@login_required
def unfollow_view(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = FollowerModel.objects.filter(follower=follower_user, following=following_user)
    already_followed.delete()
    return HttpResponseRedirect(reverse('Login_App:user', kwargs={'username':username}))

templates/Login_App/login.html
{% extends 'index.html' %}

{% load crispy_forms_tags %}

{% block title_block %} {{ title }} {% endblock %}

{% block css_block %}
<style>
    .login_form{
        width: 550px;
        border: 1px solid #ccc;
        padding: 40px;
    }

    .sign_up{
        width: 550px;
        border: 1px solid #ccc;
        padding: 20px;
    }
</style>
{% endblock %} 

{% block body_block %}
<center>
    <div class="login_form">
        <h3>Signup to see photos form your friends.</h3>
        <form action="" method="POST">
            {{ form|crispy }}
            {% csrf_token %}
            <button class="btn btn-success" type="submit" style="width: 100%;">LOGIN</button>
        </form>
    </div>
    <br>
    <div class="sign_up">
        <p>Do not have any account? <a href="{% url 'Login_App:signup' %}">Signup</a></p>
    </div>
</center>

{% endblock %}

templates/Login_App/profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}

{% block title_block %} {{ title }} {% endblock %}

{% block body_block %}

<form action="" method="POST" enctype="multipart/form-data">
    {{ form|crispy }}
    {% csrf_token %}
    <button class="btn btn-primary" type="submit">SUBMIT</button>
</form>

{% endblock %}

templates/Login_App/signup.html
{% extends 'index.html' %}

{% load crispy_forms_tags %}

{% block title_block %} {{ title }} {% endblock %}

{% block css_block %}
<style>
    .signup_form{
        width: 550px;
        border: 1px solid #ccc;
        padding: 40px;
    }

    .log_in{
        width: 550px;
        border: 1px solid #ccc;
        padding: 20px;
    }
</style>
{% endblock %} 

{% block body_block %}
<center>
    <div class="signup_form">
        <h3>Signup to see photos form your friends.</h3>
        <form action="" method="POST">
            {{ form|crispy }}
            {% csrf_token %}
            <button class="btn btn-success" type="submit" style="width: 100%;">SIGNUP</button>
        </form>
    </div>
    <br>
    <div class="log_in">
        <p>Have an account <a href="#">Lognin</a></p>
    </div>
</center>

{% endblock %}

templates/Login_App/user.html
{% extends 'navbar.html' %}

{% block title_block %}{{ user.user_profile.full_name }} @{{ user.username }} {{ title }}{% endblock %}

{% block css_block %}
    <style>
        .crop{
            width: 200px;
            height: 200px;
            overflow: hidden;
        }

        .crop img{
            width: 400px;
            height: 400px;
            margin: -75px 0 0 -100px;
        }
    </style>
{% endblock %}

{% block body_block %}
<div class="row">
    <div class="col-sm-4">
        {% if user.user_profile.profile_pic %}
        <img class="rounded-circle" src="/media/{{ user.user_profile.profile_pic }}" alt="" width="250px">
        {% else %}
        <img class="rounded-circle" src="/media/avatar.jpg" alt="" width="250px">
        {% endif %}
    </div>
    <div class="col-sm-8">
        <h3>{{ user.username }} &nbsp; <a class="btn btn-primary" href="{% url 'Login_App:edit' %}">Edit profile</a></h3>
        <br>
        <h4>{{ user.post.count }} posts &nbsp; &nbsp; {{ user.following.count }} followers &nbsp; &nbsp; {{ user.follower.count }} following</h4>
        <br>
        <h4>{{ user.user_profile.full_name }}</h4>
        <h6>{{ user.user_profile.description|linebreaks }}</h6>
        <hr>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Create Post
        </button>
    </div>
  
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Create a new post</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="POST" enctype="multipart/form-data">
                        {{ form.as_p }}
                        {% csrf_token %}
                        <button class="btn btn-success" type="submit">POST</button>
                    </form>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<br>
<div class="row">
    {% for post in user.post.all %}
    <div class="crop">
        <img src="/media/{{ post.post_image }}" alt="" title="{{ post.caption }}">
    </div>
    {% endfor %}
</div>
<br>
{% endblock %}

templates/Login_App/user_other.html
{% extends 'navbar.html' %}

{% block title_block %}@{{ title }}{% endblock %}

{% block css_block %}
    <style>
        .crop{
            width: 200px;
            height: 200px;
            overflow: hidden;
        }

        .crop img{
            width: 400px;
            height: 400px;
            margin: -75px 0 0 -100px;
        }
    </style>
{% endblock %}

{% block body_block %}
<div class="row">
    <div class="col-sm-4">
        {% if user_other.user_profile.profile_pic %}
        <img class="rounded-circle" src="/media/{{ user_other.user_profile.profile_pic }}" alt="" width="250px">
        {% else %}
        <img class="rounded-circle" src="/media/avatar.jpg" alt="" width="250px">
        {% endif %}
    </div>
    <div class="col-sm-8">
        <h3>{{ user_other.username }} &nbsp;
            {% if not already_followed %} 
            <a class="btn btn-primary" href="{% url 'Login_App:follow' username=user_other.username %}">Follow</a>
            {% else %}
            <a class="btn btn-primary" href="{% url 'Login_App:unfollow' username=user_other.username %}">Unfollow</a>
            {% endif %}
            &nbsp; 
        </h3>
        <br>
        <h4>{{ user_other.post.count }} posts &nbsp; &nbsp; {{ user_other.following.count }} followers &nbsp; &nbsp; {{ user_other.follower.count }} following</h4>
        <br>
        <h4>{{ user_other.user_profile.full_name }}</h4>
        <h6>{{ user_other.user_profile.description|linebreaks }}</h6>
        <hr>
        <!-- Button trigger modal -->
    </div>
</div>
<br>
<br>
<div class="row">
    {% for post in user_other.post.all %}
    <div class="crop">
        <img src="/media/{{ post.post_image }}" alt="" title="{{ post.caption }}">
    </div>
    {% endfor %}
</div>
{% endblock %}