Login_App/urls.py
from django.urls import path
from Login_App import views

app_name = "Login_App"

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('edit/', views.editprofile_view, name='edit'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('user/<username>/', views.user_view, name='user'),
    path('follow/<username>/', views.follow_view,name='follow'),
    path('unfollow/<username>/', views.unfollow_view, name='unfollow'),
]

Posts_App/urls.py
from Posts_App import views
from django.urls import path


app_name = 'Posts_App'

urlpatterns = [
    path('', views.home, name='home'),
    path('like/<pk>/', views.liked_view, name='like'),
    path('unlike/<pk>/', views.unlike_view, name='unlike'),
]

Socl_Mdia_Proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from Posts_App import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('Login_App.urls')),
    path('posts/', include('Posts_App.urls')),
    path('', views.home, name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Posts_App/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class PostModel(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    post_image = models.ImageField(upload_to='post_images')
    caption = models.CharField(max_length=264, blank=True)
    upload_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-upload_date']


class LikeModel(models.Model):
    post = models.ForeignKey(PostModel, on_delete=models.CASCADE, related_name='like_post')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker')
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} : {}'.format(self.user, self.post)
    

Posts_App/forms.py
from django import forms
from Posts_App.models import PostModel

class PostForm(forms.ModelForm):
    
    class Meta:
        model = PostModel
        fields = ['post_image', 'caption']

Posts_App/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from Login_App.models import FollowerModel
from Posts_App.models import PostModel, LikeModel

# Create your views here.

@login_required
def home(request):
    following_list = FollowerModel.objects.filter(follower=request.user)
    posts = PostModel.objects.filter(author__in = following_list.values_list('following'))
    
    liked_post = LikeModel.objects.filter(user=request.user)
    liked_post_list = liked_post.values_list(flat=True)

    print(liked_post_list)

    if request.method == 'GET':
        search = request.GET.get('search', '')
        result = User.objects.filter(username__icontains = search)


    return render(request, 'Posts_App/home.html', context={'title':'Home', 'search':search, 'result':result, 'posts':posts, 'liked_post_list':liked_post_list})

@login_required
def liked_view(request, pk):
    post = PostModel.objects.get(pk=pk)
    already_liked = LikeModel.objects.filter(post=post, user=request.user)
    
    if not already_liked:
        liked_post = LikeModel(post=post, user=request.user)
        liked_post.save()

    return HttpResponseRedirect(reverse('Posts_App:home'))

@login_required
def unlike_view(request, pk):
    post = PostModel.objects.get(pk=pk)
    already_liked = LikeModel.objects.filter(post=post, user=request.user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('Posts_App:home'))

templates/Posts_App/home.html
{% extends 'navbar.html' %}

{% block title_block %}{{ title }}{% endblock %}

{% block body_block %}
    <h1>Homepage</h1>
    {% if search %}
        {% for user in result %}
            <div class="row">
                <div class="col-sm-2">
                    {% if user.user_profile.profile_pic %}
                    <img src="/media/{{ user.user_profile.profile_pic }}" width="50px" alt="">
                    {% else %}
                    <img src="/media/avatar.jpg" width="50px" alt="">
                    {% endif %}
                </div>
                <div class="col-sm-10">
                    <a href="{% url 'Login_App:user' username=user.username %}"><h5>{{ user.username }}</h5></a>
                    <h4>{{ user.user_profile.full_name }}</h4>
                </div>
            </div>
            <br>
        {% endfor %}
    {% else %}
    <div class="row">
        <div class="col-sm-8">
            {#% for author in following_list %#}
                {#% for post in author.following.post.all %#}
                {% for post in posts %}
                <div class="mt-5" style="border: 1px solid #888;">
                    <div style="padding: 10px;">
                        <h4>
                            {% if post.author.user_profile.profile_pic %} 
                            <img src="/media/{{ post.author.user_profile.profile_pic }}" width="50px" class="rounded-circle">
                            {% else %}
                            <img src="/media/avatar.jpg" width="50px" class="rounded-circle" alt="">
                            {% endif %}
                            <a href="{% url 'Login_App:user' username=post.author %}">{{ post.author }}</a>
                        </h4>
                        <hr>
                        <br>
                        <h5>{{ post.caption }}</h5>
                        <img src="/media/{{ post.post_image }}" width='50%' alt="">

                        <div style="padding: 20px;">
                            <h6>{{ post.like_post.count }} Likes</h6>
                            {% if post.pk in liked_post_list %}
                            <a href="{% url 'Posts_App:unlike' pk=post.pk %}"><i class="fa-solid fa-heart" style="font-size: 36px;"></i></a>
                            {% else %}
                            <a href="{% url 'Posts_App:like' pk=post.pk %}"><i class="fa-regular fa-heart" style="font-size: 36px;"></i></a>
                            {% endif %}
                            
                        </div>
                    </div>
                </div>
                {% endfor %}
            {#% endfor %#}
        </div>
        <div class="col-sm-4">
            <div class="row">
                <div class="col-sm-2">
                    {% if user.user_profile.profile_pic %}
                    <img src="/media/{{ user.user_profile.profile_pic }}" width="50px" alt="">
                    {% else %}
                    <img src="/media/avatar.jpg" width="50px" alt="">
                    {% endif %}
                </div>
                <div class="col-sm-10">
                    {{ user.username }}
                    <br>
                    {{ user.user_profile.full_name }}
                </div>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}