Login_App/urls.py
from django.urls import path
from Login_App import views

app_name = "Login_App"

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('edit/', views.editprofile_view, name='edit'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('user/<username>/', views.user_view, name='user'),
    path('follow/<username>/', views.follow_view,name='follow'),
    path('unfollow/<username>/', views.unfollow_view, name='unfollow'),
]

Posts_App/urls.py
from Posts_App import views
from django.urls import path


app_name = 'Posts_App'

urlpatterns = [
    path('', views.home, name='home'),
    path('like/<pk>/', views.liked_view, name='like'),
    path('unlike/<pk>/', views.unlike_view, name='unlike'),
]

Socl_Mdia_Proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from Posts_App import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('Login_App.urls')),
    path('posts/', include('Posts_App.urls')),
    path('', views.home, name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title_block %} Social {% endblock %}</title>

    <link rel="shortcut icon" href="" type="image/x-icon">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    
    {% block css_block %}

    {% endblock %}
    

</head>
<body>
    <div class="container" style="padding-top: 20px;">
        {% block body_block %}
        
        {% endblock %}
    </div>
</body>
</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title_block %} Social {% endblock %}</title>

    <link rel="shortcut icon" href="" type="image/x-icon">

    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    {% block css_block %}

    {% endblock %}

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark broder-primary border-bottom-3 bg-dark mb-5">
        <div class="container">
            <a class="navbar-brand" href="{% url 'Posts_App:home' %}">
              <!-- <img class="img img-fluid" width="100px" src="/media/favicon.png" alt=""> -->
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav fw-bold">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Posts_App:home' %}">HOME</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">ABOUT</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="#">ACADEMIC</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="#">ADMISSION</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="#">CAREER</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">CONTACT US</a>
              </li>
              &nbsp; &nbsp; &nbsp; &nbsp;
              <form class="d-flex" method="GET">
                <input class="form-control me-2" type="text" placeholder="Search" name="search">
                <button class="btn btn-primary" type="submit">Search</button>
              </form>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Login_App:logout' %}">LOGOUT</a>
              </li>
              <li class="nav-item">
                {% if user.user_profile.profile_pic %}
                <a class="nav-link" href="{% url 'Login_App:profile' %}"><img class="rounded-circle" src="/media/{{ user.user_profile.profile_pic }}" alt="" width="50px"></a>
                {% else %}
                <a class="nav-link" href="{% url 'Login_App:profile' %}"><img class="rounded-circle" src="/media/avatar.jpg" alt="" width="50px"></a>
                {% endif %}
              </li>
            </ul>
          </div>
        </div>
      </nav>

    <div class="container" style="padding: 30px 0 30px 0px;">
        {% block body_block %}
        
        {% endblock %}
    </div>

    <footer class="bg-dark">
        <div class="container">
            <div class="row">
                <div class="col-12 text-white text-center">
                    <p>All Copyright is preserved © To Md Sha Newaz</p>
                    <p class="" id="dev_text">Developed by <a class="text-success" href="https://mdshanewaz.github.io/DarkBlackFire" target=”_blank”>Dev SAWON</a></p>
                </div>
            </div>
        </div>
    </footer>
      
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</body>
</html>